# from http://jekyllrb.com/docs/continuous-integration/
language: ruby
rvm:
  - 2.1
  - 2.2
# Assume bundler is being used
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external --only-4xx --check-html
# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
