# top level stuff you probably don't need to touch
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
safe: true

# edit here to achieve your personal greatness
url: https://about.joncjones.com
title: Jonathan Jones
author: Jonathan Jones
description: Personal blog and resume
profile_pic: profile.jpg
avatar: avatar.svg
google_analytics: UA-58456683-1
google_plus: JonathanJones646
email: jjones646@gmail.com
github: jjones646
linkedin: jonathanjones93
keybase: jjones646
# twitter: username
# stackoverflow: username
# disqus: username

# needed for travis-ci build
exclude:
  - README.md 
  - Gemfile
  - Gemfile.lock
  - LICENSE
