# top level stuff
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
safe: true
# gems: [jekyll-paginate, jekyll-auth, html-proofer]
gems: [jekyll-paginate, 'kramdown']

# edit here to achieve your personal greatness
url: https://about.joncjones.com
title: Jonathan Jones
author: Jonathan Jones
description: Personal blog and resume
profile_pic: profile.jpg
avatar: avatar2.svg
google_analytics: UA-58456683-1
google_plus: JonathanJones646
email: jjones646@gmail.com
github: jjones646
linkedin: jonathanjones93
keybase: jjones646

# needed for travis-ci build
exclude:
  - .gitignore
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - config.ru
  - vendor
