# top level stuff you probably don't need to touch
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: https://joncjones.com
title: Jonathan Jones
author: Jonathan Jones
description: Personal blog and resume
avatar: profile.jpg
google_analytics: UA-58456683-1
email: jjones646@gmail.com
github: jjones646
linkedin: jonathanjones93
keybase: jjones646
# twitter: username
# stackoverflow: username
# disqus: username

# needed for travis-ci build
exclude: [vendor]
